# ワークフローの名前
name: Go CI

# トリガーになる Github イベント
on:
  pull_request:

# ジョブ定義
jobs:
  # ジョブ名
  test:
    # ジョブ実行環境の指定
    runs-on: ubuntu-latest
    # ジョブ内で実行する step を定義
    steps:
      # リポジトリからソースコードの取得
      - uses: actions/checkout@v3
      # Go の実行環境 Set up
      - uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      # テストの実行
      - name: Run Test
        run: go test -v ./...